### ISSUE TITLE
Can't change password of admin

### ISSUE THREAD

**Issue by praul** [JulianPrieber/littlelink-custom#18]
Hi there and thanks for this software. Unfortunately, I cannot change passwords of admin (or maybe other users too).
Update profile works when leaving password field empty. If I enter any password there, I get:

`Illuminate\Database\QueryException
SQLSTATE[23000]: Integrity constraint violation: 19 CHECK constraint failed: users (SQL: update "users" set "name" = admin, "email" = admin@admin.com, "password" = $2y$10$RM6YyZ7yNSlbm3uFYeU7XuZT3GpAkavsVBVzZA78MGYZjjv8VrdiS, "littlelink_name" = admin, "littlelink_description" = admin page, "role" = Admin, "updated_at" = 2022-03-26 08:41:53 where "id" = 1)`

![image](https://user-images.githubusercontent.com/38807639/160231877-41e01163-6b3f-44b0-8aef-580788de4c4a.png)

If you need more debug info, let me know.

Edit: It seems, my whole setup is broken. I'm gonna try to reinstall

**Comment by JulianPrieber** [comment]
**Thank you for using LittleLink Custom.**

This might be an error still carried over from LittleLink Admin.

Can you write to the database at all (i.e. register new users or add links)?
This error appears when inserting/updating a null value in the database. I couldn't reproduce this error on Apache (Windows) yet, but I've encountered a similar issue on Linux before.

I could work around this issue by updating every field (e.g. name, password, email... etc.) maybe this works for you as well.

**Comment by praul** [comment]
Hi, no - unfortunately not. I can add links, but I cannot edit users, even with all fields filled.

**Comment by praul** [comment]
Update 2: It somewhat works when I set database to mysql. I converted the sqlite file and imported it into mysql, since the migrations button did not work.

Now, when I change admin password, I somehow lose admin capabilities. I can login, and the user role is admin, but I don't have access to the admin settings anymore

**Comment by JulianPrieber** [comment]
You might be on to something here. I have noticed before that you couldn't change the role of a user from the Admin Panel, but I haven't worked on fixing the existing system yet because I'm experimenting with replacing this system entirely. The database seeder, auth, saving and access system was written by [Khashayar](https://github.com/khashayarzavosh) for [LittleLink Admin](https://github.com/khashayarzavosh/littlelink-admin) and you can't change user roles there either. This bug has existed for a long time. 

Now, if you were to write, the user role as "Admin" instead of "admin" to the database the value would get rejected, and no change would be made effectively. This would explain the displayed behavior, but I'm not sure if this is really what's happening. I've looked into the auth section that writes to the database and I don't think this is what's causing the issue, but I will look further into this.

Now if you want to use MySQL instead of SQLite you need to run the seeder and migrations manually.
You probably want to empty your database again and run the following commands from your LittleLink Custom installation's folder:

```
php artisan migrate
php artisan db:seed 
php artisan db:seed --class="AdminSeeder"
php artisan db:seed --class="PageSeeder"
php artisan db:seed --class="ButtonSeeder"
```

**Comment by JulianPrieber** [comment]
Okay, after some testing I was able to change the role of a user, but I could only do it if I changed every value in the 'Edit User' section including the password.

**Comment by JulianPrieber** [comment]
Just released [Version v2.5.3](https://github.com/JulianPrieber/littlelink-custom/releases/tag/v2.5.3) which implements a fix for the saving values in the 'Edit User' section. 

**On the condition that your problem has been resolved with this, you can go ahead and close the issue. If you need anything else, I'm here to help.**

_If you feel like this project could offer you something, feel free to star the repo, as this really helps a lot._

**Comment by praul** [comment]
Thanks, I'm gonna try it out and report back

**Comment by praul** [comment]
Seems to be working fine. Thanks!
