### ISSUE TITLE
Can't install LLC due to SQL query not finding tables

### ISSUE THREAD

**Issue by Permanently** [JulianPrieber/littlelink-custom#308]
Platform: `Ubuntu 22.04 LTS`
Server type: `Apache2`
PHP version: `8.1.14`
MySQL version: `10.6.11-MariaDB`

Upon trying to install LLC, one of two things happen:

Installing normally, which [returns this error](https://criminal.host/s4y2jfh98w0l.mp4).

Installing, trying to fix by dropping the tables and then running migrations again, which [returns this error](https://criminal.host/wb7kxoww3fjm.mp4).

**Comment by JulianPrieber** [comment]
Could you try setting up a fresh install then accessing the first setup page but before changing anything add `/skip` to your URL (i.e. `example.com/skip`) and see if that fixes the error?

Your database type should definitely be compatible with LLC. Please make sure you fulfill all the necessary requirements to run the app https://docs.littlelink-custom.com/getting-started/requirements/.

If you really want to pinpoint where the issue lies, try the same setup with a docker instance if you didn't already try this.

**Comment by Permanently** [comment]
Really strange behaviour. I removed the root directory, unzipped again from the download provided, and... everything worked completely fine. No `/skip` or anything, I just went through the normal procedures and it worked fine again. I'm absolutely baffed.

This also fixed #300 somehow. I'm genuinely in awe as to how.
